# Generated by Django 4.2.5 on 2023-09-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
