# Generated by Django 4.2.5 on 2023-09-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('genDate', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('itunes_type', models.CharField(max_length=50)),
                ('copy_right', models.CharField(max_length=100)),
                ('explicit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pubDate', models.DateTimeField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('itunes_subtitle', models.TextField(blank=True, null=True)),
                ('itunes_keywords', models.TextField(blank=True, null=True)),
                ('itunes_image', models.CharField(max_length=400)),
                ('category', models.ManyToManyField(to='podcast.category')),
                ('podcast_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.podcastauthor')),
                ('podcast_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.generator')),
                ('podcast_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='podcast.image')),
            ],
            bases=('main.basemodel',),
        ),
    ]
