# Generated by Django 4.2.5 on 2023-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasturl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
