# Generated by Django 4.2.5 on 2023-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
