# Generated by Django 4.2.5 on 2023-09-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
