# Generated by Django 4.2.5 on 2023-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(max_length=20000),
        ),
    ]
