# Generated by Django 4.2.5 on 2023-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='author',
            new_name='podcast_author',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
    ]
