# Generated by Django 4.2.5 on 2023-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_podcast_description'),
        ('episode', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='object_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='episodes',
            field=models.ManyToManyField(to='episode.episode'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='podcasts',
            field=models.ManyToManyField(to='podcast.podcast'),
        ),
    ]
