# Generated by Django 4.2.5 on 2023-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_playlist_episodes_alter_playlist_podcasts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
